// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZIJiNUePoixsbYW9WssrnL88KISj1fJY',
    appId: '1:842862736909:web:a11eab244b020f38fd0744',
    messagingSenderId: '842862736909',
    projectId: 'flowtick-8310a',
    authDomain: 'flowtick-8310a.firebaseapp.com',
    storageBucket: 'flowtick-8310a.firebasestorage.app',
    measurementId: 'G-HC83PHMN2N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1zxDpBZ1LdiVd2E6Ym9FOrX_mlxpnYEM',
    appId: '1:842862736909:android:8d2707016b03ea7cfd0744',
    messagingSenderId: '842862736909',
    projectId: 'flowtick-8310a',
    storageBucket: 'flowtick-8310a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVk9eGs7QnLVp0rSAR5lK7CQp1v6SKlhM',
    appId: '1:842862736909:ios:b11559cce8b78261fd0744',
    messagingSenderId: '842862736909',
    projectId: 'flowtick-8310a',
    storageBucket: 'flowtick-8310a.firebasestorage.app',
    iosBundleId: 'com.example.flowtick',
  );
}
